(()=>{
const W=1500,H=1000,canvas=document.querySelector('#canvas'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const template=window.MagazineTemplates.classicFantasy;
const shotNames=template.frameLabels;
const initialTexts={
 kicker:'FANTASY MMORPG  •  HOUSING SPECIAL', title:'Brionac', subtitle:'A Place to Talk, A Home to Belong', catchcopy:'ここは、\n語らいが生まれる特別な場所。', rightcopy:'住まいは、もうひとつの冒険――',
 longtitle:'訪れるすべての冒険者へ。', longbody:'Brionacは、語らいと出会いが生まれる、冒険者のための居場所。\nはじめての方も、久しぶりの方も、どうぞ気軽にお越しください。\nここでの時間が、あなたの冒険を少しでも豊かに彩りますように。',
 n1:'01',h1:'外観',b1:'静かな街並みに佇む、Brionacの外観。\n温かな灯りが冒険者たちを優しく迎えます。\nここから、特別なひとときがはじまります。',
 n2:'02',h2:'エントランス',b2:'訪れた瞬間から感じる、やさしい灯りと温かな空気。\nBrionacの入口で、あなたをお迎えします。',
 n3:'03',h3:'待合席',b3:'旅の合間に、ほっとひと息。\nゆったりと腰を下ろし、新しい出会いを楽しめる待合席です。',
 n4:'04',h4:'オープン席のフロアへ行くためのエレベーター',b4:'さあ、もう少しだけ上へ。\nエレベーターで、にぎやかなオープン席のフロアへご案内します。',
 n5:'05',h5:'半個室のオープン席',b5:'ほどよい距離感で語らえる、半個室タイプのオープン席。\n仲間との語らいや、ゆったりとしたひとときを。',
 n6:'06',h6:'内勤スタッフが詰めている事務所',b6:'Brionacを支えるスタッフの拠点です。\nご案内やご相談など、お気軽にお声がけください。'
};
const T=(id,key,x,y,w,h,size,opt={})=>({id,type:'text',key,x,y,w,h,size,font:opt.font||'serif',color:opt.color||'#35261b',weight:opt.weight||'400',italic:!!opt.italic,align:opt.align||'left',lineHeight:opt.lineHeight||1.35,letterSpacing:opt.letterSpacing||0,free:!!opt.free,z:opt.z||20});
const F=(id,x,y,w,h)=>({id,type:'frame',x,y,w,h,scale:1,ox:0,oy:0,data:null,img:null,z:10});
let state,selected=null,history=[],future=[],drag=null,dirtyTimer=null,bg=new Image();
function fresh(){return {template:'classicFantasy',texts:{...initialTexts},frames:[F('frame1',52,350,650,310),F('frame2',795,78,290,170),F('frame3',1125,78,320,170),F('frame4',835,385,330,158),F('frame5',780,668,305,160),F('frame6',1120,668,325,160)],elements:[
T('kicker','kicker',52,30,580,44,18,{font:'Georgia,serif',letterSpacing:3}),T('title','title',76,118,570,112,78,{font:'Georgia,serif',italic:true}),T('subtitle','subtitle',120,226,510,34,16,{font:'Georgia,serif',align:'center',letterSpacing:1}),T('catchcopy','catchcopy',115,270,500,72,21),T('rightcopy','rightcopy',1010,28,420,34,15,{align:'right'}),
T('cap1','h1',80,670,560,38,23),T('body1','b1',88,711,565,64,13),T('longtitle','longtitle',210,790,430,42,26),T('longbody','longbody',210,840,455,105,13),
T('cap2','h2',795,255,280,32,18),T('body2','b2',795,289,290,68,12),T('cap3','h3',1125,255,310,32,18),T('body3','b3',1125,289,310,68,12),
T('cap4','h4',835,550,380,54,17),T('body4','b4',835,604,380,58,12),T('cap5','h5',780,834,305,36,17),T('body5','b5',780,874,305,68,12),T('cap6','h6',1120,834,325,42,16),T('body6','b6',1120,879,325,65,12)],freeImages:[],settings:{detail:false,guides:true,grid:false,snap:true,gridSize:25,disclaimer:true}}}
function safeClone(v){return JSON.parse(JSON.stringify(v,(k,x)=>k==='img'?undefined:x))}
function snapshot(){history.push(safeClone(state));if(history.length>30)history.shift();future=[]}
function restore(s){state=s;rehydrate();buildControls();syncSettings();render();autoSave()}
function undo(){if(!history.length)return;future.push(safeClone(state));restore(history.pop())} function redo(){if(!future.length)return;history.push(safeClone(state));restore(future.pop())}
function rehydrate(){[...state.frames,...state.freeImages].forEach(o=>{if(o.data){o.img=new Image();o.img.onload=render;o.img.src=o.data}})}
function paper(c,scale=1){c.save();c.scale(scale,scale);c.fillStyle='#f2eadb';c.fillRect(0,0,W,H);if(bg.complete&&bg.naturalWidth)c.drawImage(bg,0,0,W,H);else{let g=c.createLinearGradient(0,0,W,H);g.addColorStop(0,'rgba(255,255,255,.28)');g.addColorStop(.5,'rgba(184,151,92,.05)');g.addColorStop(1,'rgba(103,72,36,.08)');c.fillStyle=g;c.fillRect(0,0,W,H)}c.strokeStyle='#b58a3e';c.lineWidth=2;c.strokeRect(13,13,W-26,H-26);c.strokeStyle='rgba(181,138,62,.45)';c.lineWidth=1;c.strokeRect(20,20,W-40,H-40);let gut=c.createLinearGradient(715,0,785,0);gut.addColorStop(0,'transparent');gut.addColorStop(.48,'rgba(55,35,18,.18)');gut.addColorStop(.52,'rgba(255,255,255,.18)');gut.addColorStop(1,'transparent');c.fillStyle=gut;c.fillRect(710,0,80,H);c.restore()}
function drawFrame(c,f,exporting=false,s=1){c.save();c.scale(s,s);c.beginPath();c.rect(f.x,f.y,f.w,f.h);c.clip();c.fillStyle='#ddd3c2';c.fillRect(f.x,f.y,f.w,f.h);if(f.img&&f.img.complete){let fit=Math.max(f.w/f.img.naturalWidth,f.h/f.img.naturalHeight),dw=f.img.naturalWidth*fit*f.scale,dh=f.img.naturalHeight*fit*f.scale;let dx=f.x+(f.w-dw)/2+f.ox,dy=f.y+(f.h-dh)/2+f.oy;c.drawImage(f.img,dx,dy,dw,dh)}else{c.fillStyle='#d9d0c0';c.fillRect(f.x,f.y,f.w,f.h);c.fillStyle='#807462';c.textAlign='center';c.font='600 14px sans-serif';c.fillText('クリックしてSSを選択',f.x+f.w/2,f.y+f.h/2-3);c.font='11px sans-serif';c.fillStyle='#9a8d7a';c.fillText('IMAGE '+f.id.replace('frame','').padStart(2,'0'),f.x+f.w/2,f.y+f.h/2+19)}c.restore();c.save();c.scale(s,s);c.strokeStyle='#b18431';c.lineWidth=4;c.strokeRect(f.x,f.y,f.w,f.h);c.strokeStyle='#f8e7b6';c.lineWidth=1;c.strokeRect(f.x+6,f.y+6,f.w-12,f.h-12);for(const [x,y,sx,sy] of [[f.x+9,f.y+9,1,1],[f.x+f.w-9,f.y+9,-1,1],[f.x+9,f.y+f.h-9,1,-1],[f.x+f.w-9,f.y+f.h-9,-1,-1]]){c.save();c.translate(x,y);c.scale(sx,sy);c.strokeStyle='#c39a4e';c.lineWidth=2;c.beginPath();c.moveTo(0,12);c.quadraticCurveTo(0,0,12,0);c.moveTo(0,7);c.quadraticCurveTo(7,7,7,0);c.stroke();c.restore()}c.restore()}
function wrapLines(c,text,maxWidth,letter=0){const out=[];for(const para of String(text||'').split('\n')){let line='';for(const ch of para||' '){let test=line+ch,measure=c.measureText(test).width+Math.max(0,test.length-1)*letter;if(measure>maxWidth&&line){out.push(line);line=ch}else line=test}out.push(line)}return out}
function drawText(c,e,exporting=false,s=1,warnings=[]){let value=state.texts[e.key]??e.text??'';if(/^cap[1-6]$/.test(e.id)){let n=e.id.slice(3);value=(state.texts['n'+n]||n.padStart(2,'0'))+'   '+value}c.save();c.scale(s,s);c.font=`${e.italic?'italic ':''}${e.weight||400} ${e.size}px ${e.font}`;c.fillStyle=e.color;c.textAlign=e.align;c.textBaseline='top';let lines=wrapLines(c,value,e.w,e.letterSpacing),lh=e.size*e.lineHeight,x=e.align==='center'?e.x+e.w/2:e.align==='right'?e.x+e.w:e.x;lines.forEach((line,i)=>{if((i+1)*lh<=e.h+2){if(e.letterSpacing&&e.align==='left'){let xx=x;for(const ch of line){c.fillText(ch,xx,e.y+i*lh);xx+=c.measureText(ch).width+e.letterSpacing}}else c.fillText(line,x,e.y+i*lh)}});if(lines.length*lh>e.h+2)warnings.push(e.id);c.restore()}
function drawFreeImage(c,e,s=1){if(!e.img||!e.img.complete)return;c.save();c.scale(s,s);c.globalAlpha=e.opacity??1;c.drawImage(e.img,e.x,e.y,e.w,e.h);c.restore()}
function guides(c){c.save();if(state.settings.detail){if(state.settings.grid){let g=+state.settings.gridSize;c.strokeStyle='rgba(93,129,145,.16)';c.lineWidth=1;for(let x=0;x<W;x+=g){c.beginPath();c.moveTo(x,0);c.lineTo(x,H);c.stroke()}for(let y=0;y<H;y+=g){c.beginPath();c.moveTo(0,y);c.lineTo(W,y);c.stroke()}}if(state.settings.guides){c.setLineDash([8,7]);c.strokeStyle='rgba(194,84,63,.45)';c.strokeRect(50,50,W-100,H-100);c.fillStyle='rgba(190,113,62,.09)';c.fillRect(700,0,100,H);c.strokeStyle='rgba(190,113,62,.5)';c.strokeRect(700,0,100,H)}c.setLineDash([]);[...state.frames,...state.elements,...state.freeImages].forEach(e=>{c.strokeStyle='rgba(40,110,140,.45)';c.lineWidth=1;c.strokeRect(e.x,e.y,e.w,e.h)})}let e=objectById(selected);if(e&&(state.settings.detail||e.type==='text'||e.free)){c.setLineDash([]);c.strokeStyle='#3f8fff';c.lineWidth=3;c.strokeRect(e.x,e.y,e.w,e.h);c.fillStyle='#3f8fff';c.fillRect(e.x+e.w-7,e.y+e.h-7,14,14)}c.restore()}
function render(target=ctx,exporting=false,scale=1){target.clearRect(0,0,W*scale,H*scale);paper(target,scale);const warnings=[];const all=[...state.frames,...state.elements,...state.freeImages].sort((a,b)=>(a.z||0)-(b.z||0));for(const e of all){if(e.type==='frame')drawFrame(target,e,exporting,scale);else if(e.type==='text')drawText(target,e,exporting,scale,warnings);else drawFreeImage(target,e,scale)}if(state.settings.disclaimer){target.save();target.scale(scale,scale);target.font='9px sans-serif';target.fillStyle='rgba(50,40,30,.55)';target.textAlign='right';target.fillText('This tool is not affiliated with or endorsed by SQUARE ENIX.',1450,970);target.restore()}if(!exporting)guides(target);$('#overflowWarning').textContent=warnings.length?'⚠ '+warnings.length+'か所の文章が枠内に収まりません。文章量・文字サイズ・枠サイズを調整してください。':''}
function objectById(id){return [...state.frames,...state.elements,...state.freeImages].find(x=>x.id===id)}
function hit(x,y){return [...state.frames,...state.elements,...state.freeImages].sort((a,b)=>(b.z||0)-(a.z||0)).find(e=>x>=e.x&&x<=e.x+e.w&&y>=e.y&&y<=e.y+e.h)}
function pos(ev){let r=canvas.getBoundingClientRect();return{x:(ev.clientX-r.left)*W/r.width,y:(ev.clientY-r.top)*H/r.height}}
function snap(v){if(!state.settings.snap)return v;let g=+state.settings.gridSize;for(const n of [50,700,750,800,1450])if(Math.abs(v-n)<9)return n;return Math.round(v/g)*g}
canvas.addEventListener('pointerdown',e=>{let p=pos(e),o=hit(p.x,p.y);selected=o?.id||null;syncStyle();if(!o){render();return}if(o.type==='frame'&&!o.data&&!state.settings.detail){chooseFrame(o.id);render();return}snapshot();let movable=state.settings.detail||o.free||o.type==='freeImage'||o.type==='text',resizable=state.settings.detail||o.free||o.type==='freeImage'||o.type==='text',nearCorner=resizable&&Math.abs(p.x-(o.x+o.w))<22&&Math.abs(p.y-(o.y+o.h))<22;drag={id:o.id,x:p.x,y:p.y,ox:o.x,oy:o.y,ow:o.w,oh:o.h,imgox:o.ox||0,imgoy:o.oy||0,mode:nearCorner?'resize':movable?'move':o.type==='frame'&&o.data?'pan':'none'};canvas.style.cursor=drag.mode==='pan'?'grabbing':drag.mode==='move'||drag.mode==='resize'?'move':'default';canvas.setPointerCapture(e.pointerId);render()});
canvas.addEventListener('pointermove',e=>{let p=pos(e);if(!drag){let hover=hit(p.x,p.y);canvas.style.cursor=hover?.type==='text'?'move':hover?.type==='frame'&&hover.data?'grab':'default';return}let o=objectById(drag.id),dx=p.x-drag.x,dy=p.y-drag.y,textFree=o.type==='text'&&!e.ctrlKey&&!e.metaKey;if(drag.mode==='move'){o.x=textFree?drag.ox+dx:snap(drag.ox+dx);o.y=textFree?drag.oy+dy:snap(drag.oy+dy)}else if(drag.mode==='resize'){o.w=Math.max(40,textFree?drag.ow+dx:snap(drag.ow+dx));o.h=Math.max(30,textFree?drag.oh+dy:snap(drag.oh+dy))}else if(drag.mode==='pan'){o.ox=drag.imgox+dx;o.oy=drag.imgoy+dy}render()});canvas.addEventListener('pointerup',()=>{if(drag?.mode!=='none')autoSave();drag=null;canvas.style.cursor='default'});
canvas.addEventListener('dblclick',e=>{let o=hit(pos(e).x,pos(e).y);if(o?.type==='frame')chooseFrame(o.id)});canvas.addEventListener('wheel',e=>{let o=hit(pos(e).x,pos(e).y);if(o?.type==='frame'&&o.data){e.preventDefault();snapshot();o.scale=Math.max(1,Math.min(4,o.scale+(e.deltaY<0?.08:-.08)));buildImageControls();render();autoSave()}},{passive:false});
function fileData(file,cb){if(!file)return;let r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(file)}
function chooseFrame(id){let input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.onchange=()=>fileData(input.files[0],data=>{snapshot();let f=objectById(id);f.data=data;f.img=new Image();f.img.onload=render;f.img.src=data;f.scale=1;f.ox=f.oy=0;buildImageControls();autoSave()});input.click()}
function buildImageControls(){let box=$('#imageControls');box.innerHTML='';state.frames.forEach((f,i)=>{let d=document.createElement('div');d.className='shot-control';d.innerHTML=`<div class="shot-title"><b>${String(i+1).padStart(2,'0')} ${shotNames[i]}</b><span>${f.data?'設定済み':'未設定'}</span></div><div class="inline"><button class="mini choose">画像を選択</button><button class="mini reset">リセット</button></div>${[['拡大','scale',1,4,.01],['X','ox',-600,600,1],['Y','oy',-400,400,1]].map(a=>`<div class="range-row"><span>${a[0]}</span><input data-key="${a[1]}" type="range" min="${a[2]}" max="${a[3]}" step="${a[4]}" value="${f[a[1]]}"><output>${a[1]==='scale'?Math.round(f.scale*100)+'%':Math.round(f[a[1]])}</output></div>`).join('')}`;d.querySelector('.choose').onclick=()=>chooseFrame(f.id);d.querySelector('.reset').onclick=()=>{snapshot();f.data=null;f.img=null;f.scale=1;f.ox=f.oy=0;buildImageControls();render();autoSave()};d.querySelectorAll('input[type=range]').forEach(inp=>inp.oninput=()=>{f[inp.dataset.key]=+inp.value;inp.nextElementSibling.value=inp.dataset.key==='scale'?Math.round(f.scale*100)+'%':Math.round(f[inp.dataset.key]);render();autoSave()});box.append(d)})}
const basicFields=[['kicker','ページ上部小見出し'],['title','メインタイトル'],['subtitle','英語サブタイトル'],['catchcopy','日本語キャッチコピー'],['rightcopy','右ページ上部コピー']];
function field(key,label,large=false){let l=document.createElement('label');l.textContent=label;let i=document.createElement(large?'textarea':'input');if(!large)i.type='text';i.value=state.texts[key]||'';i.onfocus=()=>{selected=state.elements.find(e=>e.key===key)?.id||null;syncStyle();render()};i.oninput=()=>{state.texts[key]=i.value;render();autoSave()};l.append(i);return l}
function buildTextControls(){let box=$('#textControls');box.innerHTML='';let g=document.createElement('div');g.className='text-group';g.innerHTML='<b>基本情報</b>';basicFields.forEach(a=>g.append(field(...a,a[0]==='catchcopy')));box.append(g);for(let n=1;n<=6;n++){let d=document.createElement('div');d.className='text-group';d.innerHTML=`<b>${String(n).padStart(2,'0')} ${shotNames[n-1]}</b>`;d.append(field('n'+n,'番号'));d.append(field('h'+n,'見出し'));d.append(field('b'+n,'本文',true));box.append(d)}let l=document.createElement('div');l.className='text-group';l.innerHTML='<b>長文記事</b>';l.append(field('longtitle','見出し'));l.append(field('longbody','本文',true));box.append(l)}
function syncStyle(){let e=objectById(selected);$('#selectionName').textContent=e?.type==='text'?(e.key||'自由テキスト'):'テキストを選択してください';let disabled=e?.type!=='text';['font','fontSize','fontColor','lineHeight','letterSpacing','align','boldBtn','italicBtn','deleteSelected'].forEach(id=>$('#'+id).disabled=disabled);if(!disabled){$('#font').value=e.font;$('#fontSize').value=e.size;$('#fontColor').value=e.color;$('#lineHeight').value=e.lineHeight;$('#letterSpacing').value=e.letterSpacing;$('#align').value=e.align}}
function bindStyle(id,key,parse=v=>v){$('#'+id).addEventListener('change',()=>{let e=objectById(selected);if(e?.type!=='text')return;snapshot();e[key]=parse($('#'+id).value);render();autoSave()})}bindStyle('font','font');bindStyle('fontSize','size',Number);bindStyle('fontColor','color');bindStyle('lineHeight','lineHeight',Number);bindStyle('letterSpacing','letterSpacing',Number);bindStyle('align','align');
$('#boldBtn').onclick=()=>{let e=objectById(selected);if(e){snapshot();e.weight=e.weight==='700'?'400':'700';render();autoSave()}};$('#italicBtn').onclick=()=>{let e=objectById(selected);if(e){snapshot();e.italic=!e.italic;render();autoSave()}};
function removeSelected(){let e=objectById(selected);if(!e||(e.type==='frame'||!e.free))return;snapshot();state.elements=state.elements.filter(x=>x.id!==selected);state.freeImages=state.freeImages.filter(x=>x.id!==selected);selected=null;syncStyle();render();autoSave()}
$('#deleteSelected').onclick=removeSelected;$('#addText').onclick=()=>{snapshot();let id='text'+Date.now();state.elements.push(T(id,null,560,460,340,90,28,{free:true,font:'Georgia,serif'}));let e=state.elements.at(-1);e.text='自由テキスト';selected=id;syncStyle();render();autoSave()};
$('#addImage').onclick=()=>$('#freeImageInput').click();$('#freeImageInput').onchange=e=>fileData(e.target.files[0],data=>{snapshot();let img=new Image(),o={id:'image'+Date.now(),type:'freeImage',free:true,x:570,y:390,w:360,h:240,z:50,data,img};img.onload=render;img.src=data;state.freeImages.push(o);selected=o.id;render();autoSave();e.target.value='' });
function syncSettings(){let s=state.settings;$('#detailMode').checked=s.detail;$('#showGuides').checked=s.guides;$('#showGrid').checked=s.grid;$('#snap').checked=s.snap;$('#gridSize').value=s.gridSize;$('#showDisclaimer').checked=s.disclaimer;$('#modeBadge').textContent=s.detail?'詳細編集':'通常編集'}
[['detailMode','detail'],['showGuides','guides'],['showGrid','grid'],['snap','snap'],['showDisclaimer','disclaimer']].forEach(([id,k])=>$('#'+id).onchange=()=>{state.settings[k]=$('#'+id).checked;syncSettings();render();autoSave()});$('#gridSize').onchange=()=>{state.settings.gridSize=+$('#gridSize').value;render();autoSave()};
$$('[data-layer]').forEach(b=>b.onclick=()=>{let e=objectById(selected);if(!e||(!e.free&&e.type!=='freeImage'))return;snapshot();let zs=[...state.elements,...state.freeImages].map(x=>x.z||0);if(b.dataset.layer==='front')e.z=Math.max(...zs)+1;if(b.dataset.layer==='back')e.z=Math.min(...zs)-1;if(b.dataset.layer==='up')e.z++;if(b.dataset.layer==='down')e.z--;render();autoSave()});
function autoSave(){clearTimeout(dirtyTimer);$('#status').textContent='保存中…';dirtyTimer=setTimeout(()=>{try{localStorage.setItem('housingMagazineProject',JSON.stringify(safeClone(state)));$('#status').textContent='自動保存済み'}catch{$('#status').textContent='画像が大きいため自動保存できません'}},350)}
function download(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function saveProject(){let blob=new Blob([JSON.stringify(safeClone(state),null,2)],{type:'application/json'});download(blob,'housing-magazine-project.json')}
function exportImage(){let width=+$('#exportSize').value,scale=width/W,out=document.createElement('canvas');out.width=width;out.height=H*scale;render(out.getContext('2d'),true,scale);let fmt=$('#format').value,quality=+$('#quality').value;out.toBlob(b=>download(b,`housing-magazine-${width}x${H*scale}.${fmt==='jpeg'?'jpg':'png'}`),'image/'+fmt,quality)}
$('#saveBtn').onclick=$('#saveFromTab').onclick=saveProject;$('#exportPng').onclick=()=>{$('#format').value='png';exportImage()};$('#exportFromTab').onclick=exportImage;
$('#loadProject').onchange=e=>fileData(e.target.files[0],data=>{try{let raw=atob(data.split(',')[1]),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0)),json=new TextDecoder().decode(bytes);snapshot();restore(JSON.parse(json));e.target.value=''}catch{alert('このプロジェクトファイルを読み込めませんでした。')}});
$('#newBtn').onclick=()=>{if(confirm('現在の編集内容を消して、新規作成しますか？')){snapshot();state=fresh();selected=null;buildControls();syncSettings();render();autoSave()}};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;
$$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab-page').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab))});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();let o=objectById(selected);if(o?.free){snapshot();let n=safeClone(o);n.id=o.type+Date.now();n.x+=20;n.y+=20;if(n.data){n.img=new Image();n.img.onload=render;n.img.src=n.data}o.type==='text'?state.elements.push(n):state.freeImages.push(n);selected=n.id;render();autoSave()}return}if(e.key==='Delete'){removeSelected();return}let o=objectById(selected);if(o&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&(state.settings.detail||o.free||o.type==='text')){e.preventDefault();snapshot();let n=e.shiftKey?10:1;if(e.key==='ArrowLeft')o.x-=n;if(e.key==='ArrowRight')o.x+=n;if(e.key==='ArrowUp')o.y-=n;if(e.key==='ArrowDown')o.y+=n;render();autoSave()}});
function buildControls(){buildImageControls();buildTextControls();syncStyle()}
try{state=JSON.parse(localStorage.getItem('housingMagazineProject'))||fresh()}catch{state=fresh()}rehydrate();bg.onload=render;bg.src=template.background;buildControls();syncSettings();render();
})();
